config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import ContactsView, HomePageView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomePageView.as_view(), name="home"),
    path("contacts.html", ContactsView.as_view(), name="contacts"),
    path("clients/", include("clients.urls", namespace="clients")),
    path("mailings/", include("mailings.urls", namespace="mailings")),
    path("messages_list/", include("messages_list.urls", namespace="messages")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path

from mailings.apps import MailingsConfig

from .views import (MailingConfirmSendView, MailingCreateView,
                    MailingDeleteView, MailingDetailView, MailingListView,
                    MailingSendView, MailingStatusUpdateView,
                    MailingStatusView, MailingUpdateView)

app_name = MailingsConfig.name

urlpatterns = [
    path("", MailingListView.as_view(), name="mailing_list"),
    path("<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path("create/", MailingCreateView.as_view(), name="mailing_create"),
    path("<int:pk>/update/", MailingUpdateView.as_view(), name="mailing_update"),
    path("<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"),
    path("<int:pk>/send/", MailingSendView.as_view(), name="mailing_send"),
    path("<int:pk>/status/", MailingStatusView.as_view(), name="mailing_status"),
    path(
        "<int:pk>/confirm_send/",
        MailingConfirmSendView.as_view(),
        name="mailing_confirm_send",
    ),
    path(
        "<int:pk>/update-status/",
        MailingStatusUpdateView.as_view(),
        name="mailing_status_update",
    ),
]

newsletter/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, NewsletterListView, NewsletterCreateView, MessageCreateView, MessageListView, CustomerListView, CustomerCreateView
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('newsletters/', NewsletterListView.as_view(), name='newsletter_list'),
    path('newsletters/create/', NewsletterCreateView.as_view(), name='create_newsletter'),
    path('messages/create/', MessageCreateView.as_view(), name='create_message'),
    path('messages/', MessageListView.as_view(), name='message_list'),
    path('customers/', CustomerListView.as_view(), name='customer_list'),
    path('customers/create/', CustomerCreateView.as_view(), name='create_customer'),
    path('accounts/', include('allauth.urls')),
    path('manager/', views.manager_view, name='manager_view'),
    path('assign_permission/<int:newsletter_id>/<str:username>/', views.assign_permission_view, name='assign_permission'),
]

urlpatterns += [
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

users/urls.py
from django.contrib.auth.views import (LogoutView, PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from mailings.views import DisableMailingView

from .views import (ActivateUserView, BlockUserView, CustomLoginView,
                    DeactivateUserView, ProfileEditView, ProfileView,
                    RegisterView, UsersListView, email_verification)

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="home"), name="logout"),
    path("profile/<int:pk>", ProfileView.as_view(), name="profile"),
    path("profile/edit/", ProfileEditView.as_view(), name="edit_profile"),
    path(
        "confirm-registration/<str:token>/",
        email_verification,
        name="confirm-registration",
    ),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("users/", UsersListView.as_view(), name="users_list"),
    path("activate/<int:pk>/", ActivateUserView.as_view(), name="activate_user"),
    path("deactivate/<int:pk>/", DeactivateUserView.as_view(), name="deactivate_user"),
    path("block_user/<int:user_id>/", BlockUserView.as_view(), name="block_user"),
    path(
        "disable_mailing/<int:mailing_id>/",
        DisableMailingView.as_view(),
        name="disable_mailing",
    ),
]

mailings/models.py
from django.contrib.auth import get_user_model
from django.db import models

from clients.models import Client
from messages_list.models import Message


class Mailing(models.Model):
    """
    Модель для рассылок
    """
    objects: models.Manager = models.Manager()
    STATUS_CHOICES = [
        ("Создана", "Создана"),
        ("Запущена", "Запущена"),
        ("Завершена", "Завершена"),
    ]

    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="Создана")
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    recipients = models.ManyToManyField(Client)
    owner = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name="Рассылки",
        verbose_name="Владелец",
    )

    def __str__(self):
        return f"Рассылка {self.id} ({self.status})"

    def is_owned_by(self, user):
        """Проверяет, является ли пользователь владельцем рассылки."""
        return self.owner == user

    class Meta:
        verbose_name = "рассылка"
        verbose_name_plural = "рассылки"
        permissions = [("can_disable_mailing", "Can disable mailing")]


class MailingAttempt(models.Model):
    """
    Модель для попыток рассылок
    """
    objects: models.Manager = models.Manager()
    STATUS_CHOICES = [
        ("Успешно", "Успешно"),
        ("Не успешно", "Не успешно"),
    ]

    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE)
    recipient = models.ForeignKey(Client, on_delete=models.CASCADE)
    attempt_time = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    response = models.TextField()

    def __str__(self):
        return f"Попытка {self.id} для рассылки {self.mailing.id}"

    class Meta:
        verbose_name = "попытка рассылки"
        verbose_name_plural = "попытки рассылок"

mailings/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from config.forms.forms import MailingForm
from .mixins import OwnerOrManagerMixin, OwnerMixin

from .models import Mailing, MailingAttempt
from .services import send_mailing


def send_mailing_view(request, pk):
    mailing = get_object_or_404(Mailing, pk=pk)
    send_mailing(mailing)

    return redirect(reverse("mailings:mailing_status", args=[pk]))


class MailingListView(LoginRequiredMixin, ListView):
    """
    Представление списка всех рассылок
    """
    model = Mailing
    template_name = "mailings/mailings_list.html"
    context_object_name = "mailings"

    def get_queryset(self):
        # Проверяем, принадлежит ли пользователь к группе "менеджеров"
        if self.request.user.groups.filter(name="Managers").exists():
            # Если принадлежит к группе "менеджеры", показываем все клиенты
            return Mailing.objects.all()
        else:
            # Если не принадлежит, показываем только клиенты текущего пользователя
            return Mailing.objects.filter(owner=self.request.user)


class MailingStatusUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    Представление для изменения статуса рассылки
    """
    model = Mailing
    fields = []  # Поля для изменения из формы
    template_name = "mailings/mailing_status_update.html"

    def test_func(self):
        # Только менеджеры имеют доступ
        return self.request.user.groups.filter(name="Managers").exists()

    def post(self, request, *args, **kwargs):
        mailing = get_object_or_404(Mailing, pk=self.kwargs["pk"])
        action = request.POST.get("action")

        if action == "activate":
            mailing.status = "Запущена"
            messages.success(request, f"Рассылка '{mailing}' успешно запущена.")
        elif action == "deactivate":
            mailing.status = "Завершена"
            messages.success(request, f"Рассылка '{mailing}' успешно завершена.")
        mailing.save()
        return redirect("mailings:mailing_list")


@method_decorator(cache_page(60 * 15), name='dispatch')
class MailingDetailView(LoginRequiredMixin, OwnerOrManagerMixin, DetailView):
    """
    Представление просмотра рассылки
    """
    model = Mailing
    template_name = "mailings/mailings_detail.html"

    def test_func(self):
        mailing = get_object_or_404(Mailing, id=self.kwargs["pk"])
        return mailing.owner == self.request.user or self.request.user.groups.filter(name="Managers").exists()

    def handle_no_permission(self):
        raise Http404("У вас нет доступа к этой рассылке.")


class MailingCreateView(CreateView):
    """
    Представление для создания рассылки
    """
    model = Mailing
    form_class = MailingForm
    template_name = "mailings/mailing_form.html"
    success_url = reverse_lazy("mailings:mailing_list")

    def get_form_kwargs(self):
        """Передаём пользователя в форму через kwargs."""
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user  # Добавляем текущего пользователя
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = False  # Для создания рассылки
        return context

    def form_valid(self, form):
        # Устанавливаем владельцем текущего пользователя
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, OwnerMixin, UpdateView):
    """
    Представление для изменения рассылки
    """
    model = Mailing
    form_class = MailingForm
    template_name = "mailings/mailing_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = True  # Для редактирования клиента
        return context

    def get_form_kwargs(self):
        """Передаём пользователя в форму через kwargs."""
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user  # Добавляем текущего пользователя
        return kwargs

    def test_func(self):
        mailing = get_object_or_404(Mailing, id=self.kwargs["pk"])
        return mailing.owner == self.request.user

    def handle_no_permission(self):
        raise Http404("У вас нет доступа к этой рассылке.")

    def get_success_url(self):
        """
        Переопределение метода редиректа после успешного изменения статьи
        """
        return reverse("mailings:mailing_detail", kwargs={"pk": self.object.pk})


class MailingConfirmSendView(DetailView):
    """
    Представление для подтверждения запуска рассылки
    """
    model = Mailing
    template_name = "mailings/mailing_confirm_send.html"


class MailingDeleteView(LoginRequiredMixin, OwnerMixin, DeleteView):
    """
    Представление для удаления рассылки
    """
    model = Mailing
    template_name = "mailings/mailings_confirm_delete.html"
    success_url = reverse_lazy("mailings_list")

    def test_func(self):
        mailing = get_object_or_404(Mailing, id=self.kwargs["pk"])
        return mailing.owner == self.request.user

    def handle_no_permission(self):
        raise Http404("У вас нет доступа к этой рассылке.")


class MailingSendView(View):
    """
    Представление для запуска рассылки
    """
    def get(self, request, pk):
        mailing = get_object_or_404(Mailing, pk=pk)

        # Проверка статуса перед отправкой
        if mailing.status == "Запущена":
            messages.warning(request, "Рассылка уже запущена.")
        else:
            send_mailing(mailing)
            mailing.status = "Запущена"
            mailing.save()
            messages.success(request, "Рассылка успешно отправлена.")

        return redirect(reverse("mailings:mailing_status", args=[pk]))


class MailingStatusView(DetailView):
    """
    Представление для страницы статуса рассылки
    """
    model = Mailing
    template_name = "mailings/mailing_status.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Получаем все попытки отправки для данной рассылки
        context["attempts"] = MailingAttempt.objects.filter(mailing=self.object)
        return context


class DisableMailingView(LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Представление для отключения рассылок
    """
    def test_func(self):
        # Проверка, что пользователь является менеджером
        return self.request.user.is_staff

    def post(self, request, mailing_id):
        mailing = get_object_or_404(Mailing, id=mailing_id)
        mailing.status = "Завершена"  # Закрываем рассылку
        mailing.save()
        return redirect("mailings:all_mailings")

mailings/templates/mailings/mailing_confirm_send.html
{% extends 'base_templates/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <h1 class="card-title text-center">Сейчас будет запущена рассылка "{{ mailing.message }}"!</h1>
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-6">
                <div class="card shadow-sm w-100">
<!--                    <img src="{{ clients.preview_image | media_filter }}" class="img-fluid" style="height: 400px; object-fit: cover; width: 100%;">-->
                    <div class="card-body">
                        <p class="card-text">Начало: {{ mailing.start_time }}</p>
                        <p class="card-text">Окончание: {{ mailing.end_time }}</p>
                        <p class="card-text">Статус: {{ mailing.status }}</p>
                        <p class="card-text">Сообщение: {{ mailing.message }}</p>
                        <p class="card-text">Получатели:</p>
                            <ul>
                                {% for recipient in mailing.recipients.all %}
                                    <li>{{ recipient.full_name }} - {{ recipient.email }}</li>
                                {% empty %}
                                    <li>Нет получателей для этой рассылки.</li>
                                {% endfor %}
                            </ul>
                        <div class="d-flex justify-content-between align-items-center">
                            <a class="btn btn-primary" href="{% url 'mailings:mailing_list' %}" role="button">Обратно к списку</a>
                            <a class="btn btn-danger" href="{% url 'mailings:mailing_send' mailing.id %}" role="button">Запустить сейчас</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/mailing_form.html
{% extends 'base_templates/base.html' %}
{% load my_tags %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-4">
        {% if is_update %}
            Редактирование рассылки
        {% else %}
            Создание рассылки
        {% endif %}
    </h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.non_field_errors }}

        <div class="mb-3">
            <label for="id_start_time" class="form-label">Начало</label>
            {{ form.start_time|add_class:"form-control" }}
            {{ form.start_time.errors }}
        </div>

        <div class="mb-3">
            <label for="id_end_time" class="form-label">Окончание</label>
            {{ form.end_time|add_class:"form-control" }}
            {{ form.end_time.errors }}
        </div>

        <div class="mb-3">
            <label for="id_status" class="form-label">Статус</label>
            {{ form.status|add_class:"form-control" }}
            {{ form.status.errors }}
        </div>

        <div class="mb-3">
            <label for="id_message" class="form-label">Сообщение</label>
            {{ form.message|add_class:"form-control" }}
            {{ form.message.errors }}
        </div>

        <div class="mb-3">
            <label for="id_recipients" class="form-label">Получатели</label>
            {{ form.recipients|add_class:"form-control" }}
            {{ form.recipients.errors }}
        </div>

        <button type="submit" class="btn btn-primary">Сохранить</button>

        <a class="btn btn-primary"
           href="{% if is_update %}{% url 'mailings:mailing_detail' mailing.pk %}{% else %}{% url 'mailings:mailing_list' %}{% endif %}"
           role="button">Назад</a>
    </form>
</div>
{% endblock %}

mailings/templates/mailings/mailing_status.html
{% extends 'base_templates/base.html' %}
{% block content %}
<a href="{% url 'mailings:mailing_list' %}" class="btn btn-primary">Назад к списку рассылок</a>
<h2>Статус рассылки #{{ mailing.id }}</h2>
<p>Статус: {{ mailing.status }}</p>
<h3>Попытки отправки:</h3>
<table class="table">
    <thead>
    <tr>
        <th>Дата и время</th>
        <th>Имя получателя</th>
        <th>Email получателя</th>
        <th>Статус</th>
        <th>Ответ сервера</th>
    </tr>
    </thead>
    <tbody>
    {% for attempt in attempts %}
    <tr>
        <td>{{ attempt.attempt_time }}</td>
        <td>{{ attempt.recipient.full_name }}</td>  <!-- Имя получателя -->
        <td>{{ attempt.recipient.email }}</td>      <!-- Email получателя -->
        <td>{{ attempt.status }}</td>
        <td>{{ attempt.response }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<a href="{% url 'mailings:mailing_list' %}" class="btn btn-primary">Назад к списку рассылок</a>
{% endblock %}

mailings/templates/mailings/mailings_confirm_delete.html
{% extends 'base_templates/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container mt-5 text-center">
    <h2 class="mb-4">Удаление рассылки!</h2>

    <p class="card-text">Вы уверены, что хотите удалить рассылку '{{ object.subject }}'?</p>

    <form method="post" class="d-flex justify-content-center">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger me-2">Удалить</button>
        <a class="btn btn-secondary" href="{% url 'messages:message_list' %}" role="button">Отмена</a>
    </form>
</div>
{% endblock %}

mailings/templates/mailings/mailings_detail.html
{% extends 'base_templates/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-6">
                <div class="card shadow-sm w-100">
                    <!--                    <img src="{{ clients.preview_image | media_filter }}" class="img-fluid" style="height: 400px; object-fit: cover; width: 100%;">-->
                    <div class="card-body">
                        {% if mailing.status == 'Создана' and user == mailing.owner %}
                        <a class="btn btn-danger" href="{% url 'mailings:mailing_confirm_send' mailing.id %}"
                           role="button">Запустить рассылку</a>
                        {% endif %}
                        <a class="btn btn-primary" href="{% url 'mailings:mailing_status'  mailing.pk%}" role="button">Статистика</a>
                        <h1 class="card-title text-center">{{ mailing.message }}</h1>
                        <p class="card-text">Начало: {{ mailing.start_time }}</p>
                        <p class="card-text">Окончание: {{ mailing.end_time }}</p>
                        <p class="card-text">Статус: {{ mailing.status }}</p>
                        <p class="card-text">Сообщение: {{ mailing.message }}</p>
                        <p class="card-text">Получатели:</p>
                        <ul>
                            {% for recipient in mailing.recipients.all %}
                            <li>{{ recipient.full_name }} - {{ recipient.email }}</li>
                            {% empty %}
                            <li>Нет получателей для этой рассылки.</li>
                            {% endfor %}
                        </ul>
                        <div class="d-flex justify-content-between align-items-center">
                            <a class="btn btn-primary" href="{% url 'mailings:mailing_list' %}" role="button">Обратно к
                                списку</a>
                            {% if perms.users.can_disable_mailing %}
                            <form method="POST" action="{% url 'mailings:mailing_status_update' mailing.id %}">
                                {% csrf_token %}
                                {% if mailing.status != 'Завершена' %}
                                <button name="action" value="deactivate" class="btn btn-danger">Завершить</button>
                                {% endif %}
                                {% if mailing.status != 'Запущена' %}
                                <button name="action" value="activate" class="btn btn-success">Активировать</button>
                                {% endif %}
                                {% endif %}
                            </form>
                            {% if user == mailing.owner %}
                            <a class="btn btn-primary" href="{% url 'mailings:mailing_update' mailing.id %}"
                               role="button">Редактировать</a>
                            <a class="btn btn-danger" href="{% url 'mailings:mailing_delete' mailing.id %}"
                               role="button">Удалить</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/mailings_list.html
{% extends 'base_templates/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <h2 class="text-center mb-4">Список рассылок</h2>
        <h3 class="text-center mb-4">Всего рассылок: {{ mailings|length }}</h3>
        <div class="text-center mb-4">
            {% if not user|is_in_group:"Managers" %}
            <a class="btn btn-primary btn-sm" href="{% url 'mailings:mailing_create' %}"
               role="button">Добавить рассылку</a>
            {% endif %}
        </div>
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Начало</th>
                <th scope="col">Окончание</th>
                <th scope="col">Владелец</th>
                <th scope="col">Статус</th>
                <th scope="col">Сообщение</th>
                <th scope="col">Действия</th>
            </tr>
            </thead>
            <tbody>
            {% for mailing in mailings %}
            <tr>
                <td>{{ mailing.start_time }}</td>
                <td>{{ mailing.end_time }}</td>
                <td>{{ mailing.owner }}</td>
                <td>{{ mailing.status }}</td>
                <td>{{ mailing.message }}</td>
                <td>
                    <a class="btn btn-primary btn-sm" href="{% url 'mailings:mailing_detail' mailing.id %}"
                       role="button">Посмотреть</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}