clients/urls.py
from django.urls import path

from clients.apps import ClientsConfig

from .views import (ClientCreateView, ClientDeleteView, ClientDetailView,
                    ClientListView, ClientUpdateView)

app_name = ClientsConfig.name

urlpatterns = [
    path("", ClientListView.as_view(), name="client_list"),
    path("<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path("create/", ClientCreateView.as_view(), name="client_create"),
    path("<int:pk>/update/", ClientUpdateView.as_view(), name="client_update"),
    path("<int:pk>/delete/", ClientDeleteView.as_view(), name="client_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import ContactsView, HomePageView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomePageView.as_view(), name="home"),
    path("contacts.html", ContactsView.as_view(), name="contacts"),
    path("clients/", include("clients.urls", namespace="clients")),
    path("mailings/", include("mailings.urls", namespace="mailings")),
    path("messages_list/", include("messages_list.urls", namespace="messages")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path

from mailings.apps import MailingsConfig

from .views import (MailingConfirmSendView, MailingCreateView,
                    MailingDeleteView, MailingDetailView, MailingListView,
                    MailingSendView, MailingStatusUpdateView,
                    MailingStatusView, MailingUpdateView)

app_name = MailingsConfig.name

urlpatterns = [
    path("", MailingListView.as_view(), name="mailing_list"),
    path("<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path("create/", MailingCreateView.as_view(), name="mailing_create"),
    path("<int:pk>/update/", MailingUpdateView.as_view(), name="mailing_update"),
    path("<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"),
    path("<int:pk>/send/", MailingSendView.as_view(), name="mailing_send"),
    path("<int:pk>/status/", MailingStatusView.as_view(), name="mailing_status"),
    path(
        "<int:pk>/confirm_send/",
        MailingConfirmSendView.as_view(),
        name="mailing_confirm_send",
    ),
    path(
        "<int:pk>/update-status/",
        MailingStatusUpdateView.as_view(),
        name="mailing_status_update",
    ),
]

newsletter/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, NewsletterListView, NewsletterCreateView, MessageCreateView, MessageListView, CustomerListView, CustomerCreateView
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('newsletters/', NewsletterListView.as_view(), name='newsletter_list'),
    path('newsletters/create/', NewsletterCreateView.as_view(), name='create_newsletter'),
    path('messages/create/', MessageCreateView.as_view(), name='create_message'),
    path('messages/', MessageListView.as_view(), name='message_list'),
    path('customers/', CustomerListView.as_view(), name='customer_list'),
    path('customers/create/', CustomerCreateView.as_view(), name='create_customer'),
    path('accounts/', include('allauth.urls')),
    path('manager/', views.manager_view, name='manager_view'),
    path('assign_permission/<int:newsletter_id>/<str:username>/', views.assign_permission_view, name='assign_permission'),
]

urlpatterns += [
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

users/urls.py
from django.contrib.auth.views import (LogoutView, PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from mailings.views import DisableMailingView

from .views import (ActivateUserView, BlockUserView, CustomLoginView,
                    DeactivateUserView, ProfileEditView, ProfileView,
                    RegisterView, UsersListView, email_verification)

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="home"), name="logout"),
    path("profile/<int:pk>", ProfileView.as_view(), name="profile"),
    path("profile/edit/", ProfileEditView.as_view(), name="edit_profile"),
    path(
        "confirm-registration/<str:token>/",
        email_verification,
        name="confirm-registration",
    ),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("users/", UsersListView.as_view(), name="users_list"),
    path("activate/<int:pk>/", ActivateUserView.as_view(), name="activate_user"),
    path("deactivate/<int:pk>/", DeactivateUserView.as_view(), name="deactivate_user"),
    path("block_user/<int:user_id>/", BlockUserView.as_view(), name="block_user"),
    path(
        "disable_mailing/<int:mailing_id>/",
        DisableMailingView.as_view(),
        name="disable_mailing",
    ),
]

templates/base_templates/includes/inc_footer.html
<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Mailing Campaign &copy; Сервис по управлению рассылками</p>
    <p class="mb-0">Обратиться к нам можно на странице <a href="{% url 'contacts' %}">Контакты</a></p>
  </div>
</footer>

templates/base_templates/includes/inc_menu.html
<div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-md-4 py-4">
                <h4>Mailing Campaign</h4>
                <p class="text-body-secondary">Сервис по управлению рассылками.</p>
            </div>
            <div class="col-md-4 py-4">
                <ul class="list-unstyled">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <form method="post" action="{% url 'users:logout' %}" style="display:inline">
                            {% csrf_token %}
                            <li><a href="{% url 'users:profile' user.id %}" class="text-white">Мой профиль</a>
                            </li>
                            <button type="submit" class="btn btn-link nav-link">Выйти</button>
                        </form>
                    </li>
                    {% else %}
                    <li><a href="{% url 'users:login' %}" class="text-white">Вход</a></li>
                    <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-md-4 py-4">
                <h4>Меню</h4>
                <ul class="list-unstyled">
                    <li><a href="{% url 'home' %}" class="text-white">Главная</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'clients:client_list' %}" class="text-white">Клиенты</a></li>
                    <li><a href="{% url 'messages:message_list' %}" class="text-white">Сообщения</a></li>
                    <li><a href="{% url 'mailings:mailing_list' %}" class="text-white">Рассылки</a></li>
                    {% endif %}
                    {% if perms.users.can_block_user %}
                    <li><a href="{% url 'users:users_list' %}" class="text-white">Пользователи</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
        <a href="#" class="navbar-brand d-flex align-items-center">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</div>