clients/urls.py
from django.urls import path

from clients.apps import ClientsConfig

from .views import (ClientCreateView, ClientDeleteView, ClientDetailView,
                    ClientListView, ClientUpdateView)

app_name = ClientsConfig.name

urlpatterns = [
    path("", ClientListView.as_view(), name="client_list"),
    path("<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path("create/", ClientCreateView.as_view(), name="client_create"),
    path("<int:pk>/update/", ClientUpdateView.as_view(), name="client_update"),
    path("<int:pk>/delete/", ClientDeleteView.as_view(), name="client_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import ContactsView, HomePageView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomePageView.as_view(), name="home"),
    path("contacts.html", ContactsView.as_view(), name="contacts"),
    path("clients/", include("clients.urls", namespace="clients")),
    path("mailings/", include("mailings.urls", namespace="mailings")),
    path("messages_list/", include("messages_list.urls", namespace="messages")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path

from mailings.apps import MailingsConfig

from .views import (MailingConfirmSendView, MailingCreateView,
                    MailingDeleteView, MailingDetailView, MailingListView,
                    MailingSendView, MailingStatusUpdateView,
                    MailingStatusView, MailingUpdateView)

app_name = MailingsConfig.name

urlpatterns = [
    path("", MailingListView.as_view(), name="mailing_list"),
    path("<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path("create/", MailingCreateView.as_view(), name="mailing_create"),
    path("<int:pk>/update/", MailingUpdateView.as_view(), name="mailing_update"),
    path("<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"),
    path("<int:pk>/send/", MailingSendView.as_view(), name="mailing_send"),
    path("<int:pk>/status/", MailingStatusView.as_view(), name="mailing_status"),
    path(
        "<int:pk>/confirm_send/",
        MailingConfirmSendView.as_view(),
        name="mailing_confirm_send",
    ),
    path(
        "<int:pk>/update-status/",
        MailingStatusUpdateView.as_view(),
        name="mailing_status_update",
    ),
]

newsletter/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, NewsletterListView, NewsletterCreateView, MessageCreateView, MessageListView, CustomerListView, CustomerCreateView
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('newsletters/', NewsletterListView.as_view(), name='newsletter_list'),
    path('newsletters/create/', NewsletterCreateView.as_view(), name='create_newsletter'),
    path('messages/create/', MessageCreateView.as_view(), name='create_message'),
    path('messages/', MessageListView.as_view(), name='message_list'),
    path('customers/', CustomerListView.as_view(), name='customer_list'),
    path('customers/create/', CustomerCreateView.as_view(), name='create_customer'),
    path('accounts/', include('allauth.urls')),
    path('manager/', views.manager_view, name='manager_view'),
    path('assign_permission/<int:newsletter_id>/<str:username>/', views.assign_permission_view, name='assign_permission'),
]

urlpatterns += [
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

users/urls.py
from django.contrib.auth.views import (LogoutView, PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from mailings.views import DisableMailingView

from .views import (ActivateUserView, BlockUserView, CustomLoginView,
                    DeactivateUserView, ProfileEditView, ProfileView,
                    RegisterView, UsersListView, email_verification)

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="home"), name="logout"),
    path("profile/<int:pk>", ProfileView.as_view(), name="profile"),
    path("profile/edit/", ProfileEditView.as_view(), name="edit_profile"),
    path(
        "confirm-registration/<str:token>/",
        email_verification,
        name="confirm-registration",
    ),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("users/", UsersListView.as_view(), name="users_list"),
    path("activate/<int:pk>/", ActivateUserView.as_view(), name="activate_user"),
    path("deactivate/<int:pk>/", DeactivateUserView.as_view(), name="deactivate_user"),
    path("block_user/<int:user_id>/", BlockUserView.as_view(), name="block_user"),
    path(
        "disable_mailing/<int:mailing_id>/",
        DisableMailingView.as_view(),
        name="disable_mailing",
    ),
]

users/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models


class CustomUserManager(BaseUserManager):
    """
    Переопределение менеджера создания пользователей
    """

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    """
    Определение модели пользователя
    """

    username = None
    email = models.EmailField(unique=True)
    avatar = models.ImageField(upload_to="avatars/", blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    country = models.CharField(max_length=50, blank=True, null=True)

    token = models.CharField(max_length=100, verbose_name="Token", blank=True, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "пользователь"
        verbose_name_plural = "пользователи"
        ordering = ["email"]
        permissions = [("can_block_user", "Can block user")]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    """
    Форма создания пользователя
    """
    phone_number = forms.CharField(max_length=15, required=False, help_text="Help")
    usable_password = None

    class Meta:
        model = CustomUser
        fields = (
            "email",
            "first_name",
            "last_name",
            "phone_number",
            "country",
            "avatar",
            "password1",
            "password2",
        )

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get("phone_number")
        if phone_number and not phone_number.isdigit:
            raise forms.ValidationError("Wrong number")
        return phone_number


class UserProfileForm(forms.ModelForm):
    """
    Форма профиля пользователя
    """
    class Meta:
        model = CustomUser
        fields = [
            "email",
            "first_name",
            "last_name",
            "phone_number",
            "avatar",
            "country",
        ]
        widgets = {
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
            "phone_number": forms.TextInput(attrs={"class": "form-control"}),
            "avatar": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "country": forms.TextInput(attrs={"class": "form-control"}),
        }

users/views.py
import secrets

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView

from config.settings import EMAIL_HOST_USER

from .forms import CustomUserCreationForm, UserProfileForm
from .models import CustomUser


class RegisterView(CreateView):
    """
    Представление регистрации пользователя
    """
    template_name = "users/register.html"
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/confirm-registration/{token}/"
        send_mail(
            subject="Подтверждение регистрации на Perfect Mailing",
            message=f"Здравствуйте! Для подтверждения регистрации перейдите по ссылке: {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )

        messages.success(
            self.request,
            "Вы успешно зарегистрировались! Проверьте вашу почту для подтверждения регистрации."
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(CustomUser, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class CustomLoginView(LoginView):
    """
    Представление для входа
    """
    template_name = "users/login.html"
    success_url = reverse_lazy("catalog:home")


class ProfileView(LoginRequiredMixin, DetailView):
    """
    Представление для просмотра профайла
    """
    model = CustomUser
    form_class = UserProfileForm
    template_name = "users/profile.html"


class ProfileEditView(LoginRequiredMixin, UpdateView):
    """
    Представление для редактирования профайла
    """
    model = CustomUser
    form_class = UserProfileForm
    template_name = "users/edit_profile.html"
    success_url = reverse_lazy("home")

    def get_object(self, queryset=None):
        return self.request.user


class BlockUserView(LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Представление для блокировки пользователей
    """
    def test_func(self):
        # Проверка, что пользователь является менеджером
        return self.request.user.is_staff

    def post(self, request, user_id):
        user = get_object_or_404(CustomUser, id=user_id)
        user.is_active = False
        user.save()
        return redirect("users:user_list")


class UsersListView(ListView):
    """
    Представление списка пользователй
    """
    model = CustomUser
    template_name = "users/users_list.html"
    context_object_name = "users"


class ActivateUserView(UserPassesTestMixin, View):
    """
    Представление для активации пользователя
    """
    def test_func(self):
        return self.request.user.groups.filter(name="Managers").exists()

    def post(self, request, pk):
        user = get_object_or_404(CustomUser, pk=pk)
        user.is_active = True
        user.save()
        messages.success(request, f"Пользователь {user.username} был активирован.")
        return redirect("users:users_list")


class DeactivateUserView(UserPassesTestMixin, View):
    """
    Представление для деактивации пользователя
    """
    def test_func(self):
        return self.request.user.groups.filter(name="Managers").exists()

    def post(self, request, pk):
        user = get_object_or_404(CustomUser, pk=pk)
        user.is_active = False
        user.save()
        messages.success(request, f"Пользователь {user.username} был деактивирован.")
        return redirect("users:users_list")

users/templates/users/edit_profile.html
{% extends 'base_templates/base.html' %}

{% block title %}Edit Profile{% endblock %}

{% block content %}
  <div class="container">
    <h2>Edit Profile</h2>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Save changes</button>
      <a class="btn btn-secondary" href="{% url 'users:profile' user.id %}" role="button">Отмена</a>
    </form>
  </div>
{% endblock %}

users/templates/users/home.html
{% extends 'base_templates/base.html' %}
{% load my_tags %}
{% block content %}
<h1 class="text-center">Главная страница</h1>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-12 col-sm-8 col-md-6 col-lg-4 mx-auto">
                <div class="card shadow-sm">
                    <div class="card-body text-center">
                        <p>Всего рассылок: {{ total_mailings }}</p>
                        <p>Активных рассылок: {{ active_mailings }}</p>
                        <p>Уникальных получателей: {{ unique_recipients }}</p>
                        {% if user.is_authenticated %}
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'clients:client_list' %}" role="button">Получатели</a>
                            </div>
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'messages:message_list' %}" role="button">Сообщения</a>
                            </div>
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'mailings:mailing_list' %}" role="button">Рассылки</a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'base_templates/base.html' %}
{% load custom_filters %}
{% block title %}Login{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="card p-4 shadow" style="width: 400px;">
        <h2 class="text-center mb-4">Вход</h2>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                    {{ field|add_class:"form-control" }}
                    {% if field.help_text %}
                        <div class="form-text">{{ field.help_text }}</div>
                    {% endif %}
                    {% for error in field.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary w-100">Войти</button>
            <p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
        </form>
    </div>
</div>


{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base_templates/base.html' %}
{% load i18n %}
{% load custom_filters %}
{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="card p-4 shadow" style="max-width: 400px; width: 100%;">
        <h2 class="text-center mb-4">{% translate "Пароль успешно установлен" %}</h2>
        <div class="text-center">
            <a href="{% url 'users:login' %}" class="btn btn-primary">Войти</a>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base_templates/base.html' %}
{% load i18n static %}
{% load custom_filters %}
{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="card p-4 shadow" style="max-width: 400px; width: 100%;">
        {% if validlink %}
            <h2 class="text-center mb-4">Смена пароля</h2>
            <p class="text-muted text-center">Пожалуйста, введите новый пароль</p>

            <form method="post" class="mt-3">
                {% csrf_token %}
                <fieldset class="mb-3">
                    <input class="d-none" autocomplete="username" value="{{ form.user.get_username }}">

                    <div class="mb-3">
                        <label for="id_new_password1" class="form-label">Новый пароль</label>
                        {{ form.new_password1|add_class:"form-control" }}
                        {% for error in form.new_password1.errors %}
                            <div class="text-danger mt-1">{{ error }}</div>
                        {% endfor %}
                    </div>

                    <div class="mb-3">
                        <label for="id_new_password2" class="form-label">Подтвердите пароль</label>
                        {{ form.new_password2|add_class:"form-control" }}
                        {% for error in form.new_password2.errors %}
                            <div class="text-danger mt-1">{{ error }}</div>
                        {% endfor %}
                    </div>
                </fieldset>
                <button type="submit" class="btn btn-primary w-100">Сменить пароль</button>
            </form>
        {% else %}
            <h2 class="text-center text-danger mb-4">{% translate "Invalid Link" %}</h2>
            <p class="text-center">{% translate "The password reset link was invalid, possibly because it has already been used. Please request a new password reset." %}</p>
        {% endif %}
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'base_templates/base.html' %}
{% load i18n %}
{% load custom_filters %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="card p-4 shadow" style="max-width: 600px; width: 100%;">
        <h2 class="text-center mb-4">{% translate "Сброс пароля" %}</h2>
        <p>На указанный e-mail отправлена ссылка для восстановления пароля</p>

        <div class="text-center">
            <a href="{% url 'users:login' %}" class="btn btn-primary mt-4">На страницу входа</a>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}
{% blocktranslate %}Вы запросили восстановление пароля на сайте {{ site_name }}.{% endblocktranslate %}

{% blocktranslate %}Перейдите по следующей ссылке, чтобы сбросить пароль:{% endblocktranslate %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

{% blocktranslate %}Если вы не запрашивали восстановление пароля, проигнорируйте это письмо.{% endblocktranslate %}

users/templates/users/password_reset_form.html
{% extends 'base_templates/base.html' %}
{% load custom_filters %}
{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="card p-4 shadow" style="max-width: 400px; width: 100%;">
        <h4 class="text-center mb-4">Сброс пароля</h4>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="mb-3">
                    <label class="form-label fw-bold" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field|add_class:"form-control" }}
                    {% for error in field.errors %}
                        <div class="text-danger mt-1">{{ error }}</div>
                    {% endfor %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary w-100">Отправить</button>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'base_templates/base.html' %}
{% load users_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-6">
                <div class="card shadow-sm w-100">
                    <img src="{{ product.image | media_filter }}">
                    <div class="card-body">
                        <h1 class="card-title text-center">{{ user.first_name }}</h1>
                        <p class="card-text">Почта: {{ user.email }}</p>
                        <p class="card-text text-muted">Имя: {{ user.first_name }}</p>
                        <p class="card-text text-muted">Фамилия: {{ user.last_name }}</p>
                        <p class="card-text text-muted">Телефон: {{ user.phone_number }}</p>
                        <p class="card-text text-muted">Страна: {{ user.country }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a class="btn btn-primary" href="{% url 'users:edit_profile' %}"
                               role="button">Редактировать</a>
                            <a class="btn btn-primary" href="{% url 'users:password_reset' %}"
                               role="button">Сменить пароль</a>
                            <a class="btn btn-primary" href="{% url 'home' %}"
                               role="button">На главную</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'base_templates/base.html' %}
{% load custom_filters %}
{% block title %}Register{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="card p-4 shadow" style="width: 800px;">
        <h2 class="text-center mb-4">Регистрация</h2>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                    {{ field|add_class:"form-control" }}
                    {% if field.help_text %}
                        <div class="form-text">{{ field.help_text }}</div>
                    {% endif %}
                    {% for error in field.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary w-100">Зарегистрироваться</button>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/users_list.html
{% extends 'base_templates/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <h2 class="text-center mb-4">Список пользователей</h2>
        <h3 class="text-center mb-4">Всего пользователей: {{ users|length }}</h3>
    </div>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Имя</th>
            <th scope="col">Фамилия</th>
            <th scope="col">Email</th>
            <th scope="col">Phone number</th>
            <th scope="col">Страна</th>
            <th scope="col">Статус</th>
            <th scope="col">Действия</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
        <tr>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.phone_number }}</td>
            <td>{{ user.country }}</td>
            <td>{% if user.is_active %}Активен{% else %}Деактивирован{% endif %}</td>
            <td>
                {% if not user.is_active %}
                <form method="POST" action="{% url 'users:activate_user' user.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success">Активировать</button>
                </form>
                {% endif %}
                {% if user.is_active %}
                <form method="POST" action="{% url 'users:deactivate_user' user.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Деактивировать</button>
                </form>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}