clients/urls.py
from django.urls import path

from clients.apps import ClientsConfig

from .views import (ClientCreateView, ClientDeleteView, ClientDetailView,
                    ClientListView, ClientUpdateView)

app_name = ClientsConfig.name

urlpatterns = [
    path("", ClientListView.as_view(), name="client_list"),
    path("<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path("create/", ClientCreateView.as_view(), name="client_create"),
    path("<int:pk>/update/", ClientUpdateView.as_view(), name="client_update"),
    path("<int:pk>/delete/", ClientDeleteView.as_view(), name="client_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import ContactsView, HomePageView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomePageView.as_view(), name="home"),
    path("contacts.html", ContactsView.as_view(), name="contacts"),
    path("clients/", include("clients.urls", namespace="clients")),
    path("mailings/", include("mailings.urls", namespace="mailings")),
    path("messages_list/", include("messages_list.urls", namespace="messages")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, NewsletterListView, NewsletterCreateView, MessageCreateView, MessageListView, CustomerListView, CustomerCreateView
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('newsletters/', NewsletterListView.as_view(), name='newsletter_list'),
    path('newsletters/create/', NewsletterCreateView.as_view(), name='create_newsletter'),
    path('messages/create/', MessageCreateView.as_view(), name='create_message'),
    path('messages/', MessageListView.as_view(), name='message_list'),
    path('customers/', CustomerListView.as_view(), name='customer_list'),
    path('customers/create/', CustomerCreateView.as_view(), name='create_customer'),
    path('accounts/', include('allauth.urls')),
    path('manager/', views.manager_view, name='manager_view'),
    path('assign_permission/<int:newsletter_id>/<str:username>/', views.assign_permission_view, name='assign_permission'),
]

urlpatterns += [
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

users/urls.py
from django.contrib.auth.views import (LogoutView, PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from mailings.views import DisableMailingView

from .views import (ActivateUserView, BlockUserView, CustomLoginView,
                    DeactivateUserView, ProfileEditView, ProfileView,
                    RegisterView, UsersListView, email_verification)

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="home"), name="logout"),
    path("profile/<int:pk>", ProfileView.as_view(), name="profile"),
    path("profile/edit/", ProfileEditView.as_view(), name="edit_profile"),
    path(
        "confirm-registration/<str:token>/",
        email_verification,
        name="confirm-registration",
    ),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("users/", UsersListView.as_view(), name="users_list"),
    path("activate/<int:pk>/", ActivateUserView.as_view(), name="activate_user"),
    path("deactivate/<int:pk>/", DeactivateUserView.as_view(), name="deactivate_user"),
    path("block_user/<int:user_id>/", BlockUserView.as_view(), name="block_user"),
    path(
        "disable_mailing/<int:mailing_id>/",
        DisableMailingView.as_view(),
        name="disable_mailing",
    ),
]

clients/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Client(models.Model):
    objects: models.Manager = models.Manager()
    email = models.EmailField(unique=True)
    full_name = models.CharField(max_length=255)
    comment = models.TextField()
    owner = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name="Клиенты",
        verbose_name="Владелец",
    )

    def __str__(self):
        return f"{self.full_name}: {self.email}"

    def is_owned_by(self, user):
        """Проверяет, является ли пользователь владельцем клиента."""
        return self.owner == user

    class Meta:
        verbose_name = "клиент"
        verbose_name_plural = "клиенты"

clients/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from config.forms.forms import ClientForm

from .models import Client


class ClientListView(LoginRequiredMixin, ListView):
    """
    Представление списка всех клиентов
    """
    model = Client
    template_name = "clients/client_list.html"
    context_object_name = "clients"

    def get_queryset(self):
        # Проверяем, принадлежит ли пользователь к группе "менеджеров"
        if self.request.user.groups.filter(name="Managers").exists():
            # Если принадлежит к группе "менеджеры", показываем все клиенты
            return Client.objects.all().order_by("full_name")
        else:
            # Если не принадлежит, показываем только клиенты текущего пользователя
            return Client.objects.filter(owner=self.request.user).order_by("full_name")


@method_decorator(cache_page(60 * 15), name='dispatch')
class ClientDetailView(DetailView):
    """
    Представление детальной информации клиента
    """
    model = Client
    template_name = "clients/client_detail.html"


class ClientCreateView(CreateView):
    """
    Представление для создания клиента
    """
    model = Client
    form_class = ClientForm
    template_name = "clients/client_form.html"
    success_url = reverse_lazy("clients:client_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = False  # Для создания клиента
        return context

    def form_valid(self, form):
        # Устанавливаем владельцем текущего пользователя
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    Представление для редактирования клиентф
    """
    model = Client
    form_class = ClientForm
    template_name = "clients/client_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = True  # Для редактирования клиента
        return context

    def get_success_url(self):
        """
        Переопределение метода редиректа после успешного изменения статьи
        """
        return reverse("clients:client_detail", kwargs={"pk": self.object.pk})

    def get_object(self):
        client = get_object_or_404(Client, id=self.kwargs["pk"])
        if not client.is_owned_by(self.request.user):
            raise Http404("Вы не можете редактировать этот клиент.")
        return client

    def test_func(self):
        # Проверка, что пользователь имеет доступ
        return self.get_object().is_owned_by(self.request.user)


class ClientDeleteView(DeleteView):
    """
    Представление для удаления клиента
    """
    model = Client
    template_name = "clients/client_confirm_delete.html"
    success_url = reverse_lazy("clients:client_list")

clients/templates/clients/client_confirm_delete.html
{% extends 'base_templates/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container mt-5 text-center">
    <h2 class="mb-4">Удаление получателя!</h2>

    <p class="card-text">Вы уверены, что хотите удалить получателя '{{ object.full_name }}'?</p>

    <form method="post" class="d-flex justify-content-center">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger me-2">Удалить</button>
        <a class="btn btn-secondary" href="{% url 'clients:client_list' %}" role="button">Отмена</a>
    </form>
</div>
{% endblock %}

clients/templates/clients/client_detail.html
{% extends 'base_templates/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-6">
                <div class="card shadow-sm w-100">
                    <div class="card-body">
                        <h1 class="card-title text-center">{{ client.full_name }}</h1>
                        <p class="card-text">Почта: {{ client.email }}</p>
                        <p class="card-text">Владелец: {{ client.owner }}</p>
                        <p class="card-text text-muted">Комментарий: {{ client.comment }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a class="btn btn-primary" href="{% url 'clients:client_list' %}" role="button">Обратно к
                                списку</a>
                            {% if user == client.owner %}
                            <a class="btn btn-primary" href="{% url 'clients:client_update' client.id %}" role="button">Редактировать</a>
                            <a class="btn btn-danger" href="{% url 'clients:client_delete' client.id %}" role="button">Удалить</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

clients/templates/clients/client_form.html
{% extends 'base_templates/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container mt-5">
    <h2 class="mb-4">{% if is_update %}Редактирование клиента{% else %}Создание клиента{% endif %}</h2>
    <form method="post" enctype="multipart/form-data">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.non_field_errors }}

            <div class="mb-3">
                <label for="id_full_name" class="form-label">Имя</label>
                {{ form.full_name|add_class:"form-control" }}
                {{ form.full_name.errors }}
            </div>

            <div class="mb-3">
                <label for="id_email" class="form-label">Почта</label>
                {{ form.email|add_class:"form-control" }}
                {{ form.email.errors }}
            </div>

            <div class="mb-3">
                <label for="id_comment" class="form-label">Комментарий</label>
                {{ form.comment|add_class:"form-control" }}
                {{ form.comment.errors }}
            </div>

            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a class="btn btn-primary"
               href="{% if is_update%}{% url 'clients:client_detail' client.id %}{% else %}{% url 'clients:client_list' %}{% endif %}"
               role="button">Назад</a>
        </form>
</div>
{% endblock %}

clients/templates/clients/client_list.html
{% extends 'base_templates/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <h2 class="text-center mb-4">Список клиентов для рассылки</h2>
        <h3 class="text-center mb-4">Всего получателей: {{ clients|length }}</h3>
        <div class="text-center mb-4">
            {% if not user|is_in_group:"Managers" %}
            <a class="btn btn-primary btn-sm" href="{% url 'clients:client_create' %}" role="button">Добавить получателя</a>
            {% endif %}
        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Имя</th>
                    <th scope="col">Email</th>
                    <th scope="col">Владелец</th>
                    <th scope="col">Комментарий</th>
                    <th scope="col">Действия</th>
                </tr>
            </thead>
            <tbody>
                {% for client in clients %}
                <tr>
                    <td>{{ client.full_name }}</td>
                    <td>{{ client.email }}</td>
                    <td>{{ client.owner }}</td>
                    <td>{{ client.comment|truncatechars:100 }}</td>
                    <td>
                        <a class="btn btn-primary btn-sm" href="{% url 'clients:client_detail' client.id %}" role="button">Посмотреть</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}